# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
windowrule = match:class .*, no_blur off
windowrule = match:class ^()$, match:title ^()$, no_blur off
windowrule = match:class ^(.*)$, opacity 0.90 0.90
windowrulev = opacity 0.5 override 0.75 override, class:kitty

# ----------- Quickshell Layer Rules -----------_
layerrule = blur on, match:namespace quickshell:.*
layerrule = ignore_alpha 0.50, match:namespace quickshell:.*
layerrule = xray 0, match:namespace quickshell:.*

